- shell:
  - ['cd dotbot && git checkout master && git pull', 'Moving dotbot submodule to branch master and pulling']

- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.bashrc: bashrc
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.gvimrc: gvimrc

    ~/.zprezto: zprezto
    ~/.zlogin: zsh/zlogin
    ~/.zlogout: zsh/zlogout
    ~/.zpreztorc: zsh/zpreztorc
    ~/.zprofile: zsh/zprofile
    ~/.zshenv: zsh/zshenv
    ~/.zshrc: zsh/zshrc

    ~/.tmux.conf: tmux.conf
    ~/.vimrc: vimrc
    ~/.vimpcrc: vimpcrc

- brew:
  - git
  - exa
  - sbcl
  - leiningen

- cask:
  - iterm2
  - kitty
  - appcleaner
  - colorpicker-materialdesign
  - spotify
  - google-chrome
  - firefox
  - beaker-browser
  - iina
  - quicklook-json
  - quicklook-csv
  - virtualbox
  - spotify
  - keybase

- shell:
  - ['git submodule update --init --recursive', 'Installing submodules']
  - ['vim +PluginInstall +qall', 'Installing vim plugins']
