set nocompatible            " Make Vim useful
set encoding=utf-8 nobomb   " Use UTF-8 without BOM

autocmd! bufwritepost .vimrc source %

silent! call pathogen#infect()
silent! call pathogen#helptags()

" Plugins {{{
if has('autocmd')
    filetype indent plugin on
    nnoremap _ap :setlocal filetype=apache<CR>
    nnoremap _bi :setlocal filetype=bindzone<CR>
    nnoremap _cs :setlocal filetype=css<CR>
    nnoremap _ht :setlocal filetype=html<CR>
    nnoremap _js :setlocal filetype=javascript<CR>
    nnoremap _md :setlocal filetype=markdown<CR>
    nnoremap _pl :setlocal filetype=perl<CR>
    nnoremap _ph :setlocal filetype=php<CR>
    nnoremap _py :setlocal filetype=python<CR>
    nnoremap _rb :setlocal filetype=ruby<CR>
    nnoremap _sh :setlocal filetype=sh<CR>
    nnoremap _vi :setlocal filetype=vim<CR>
    nnoremap _xm :setlocal filetype=xml<CR>
    autocmd BufNewFile,BufReadPost *.md set filetype=markdown
endif
" }}}
" Spaces & Tabs {{{
set tabstop=4       " 4 space tab
set expandtab       " use spaces for tabs
set softtabstop=4   " 4 space tab
set shiftwidth=4    " Indenting is 4 spaces
set autoindent
set smarttab
set shiftround
set list            " Show invisibles
set listchars=tab:▸\ ,eol:¬,extends:❯,precedes:❮
" }}}
set modelines=1     " Allow set variables specific to a file
" Shortcuts {{{
let mapleader = ","
"nnoremap . <NOP>
set wildmode=list:longest
set autoread

noremap <leader>w :update<CR>       " Quick save
vnoremap <leader>w <C-C>:update<CR> " Quick save
inoremap <leader>w <C-O>:update<CR> " Quick save

noremap <leader>e :quit<CR> # Quick exit

map <leader>, <esc>:tabprevious<CR>
map <leader>. <esc>:tabnext<CR>
vnoremap <leader>s :sort<CR>
nnoremap <leader>1 :set number!<CR>
" }}}
" Command line {{{¬
set ttyfast         " Optimize for fast terminal connections
set lazyredraw      " Redraw only when we need to
set laststatus=2    " Always show status line
set number          " Enable line numbers
set ruler           " Show cursor position
set wildmenu        " Enhace command-line completion
set clipboard=unnamed " Use the OS clipboard by default (on versions compiled with `+clipboard`)
"
" }}}
" Color scheme {{{¬
if has('syntax')
    let g:solarized_contrast="high"    "default value is normal
    let g:solarized_hitrail=1           "default value is 0
    syntax enable
    set t_Co=256
    set background=light
    set noshowmode
    colorscheme solarized
    call togglebg#map("<F5>")

    " Airline > git clone https://github.com/bling/vim-airline ~/.vim/bundle/vim-airline
    let g:airline_powerline_fonts = 1
    let g:airline_theme = 'solarized'
    let g:airline_solarized_bg = 'light'
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#left_sep = ' '
    let g:airline#extensions#tabline#left_alt_sep = '|'
    let g:airline_left_sep = ''
    let g:airline_left_alt_sep = ''
    let g:airline_right_sep = ''
    let g:airline_right_alt_sep = ''
endif
"
" }}}
" Backups {{{
set nobackup " Disable backup and swap files
set nowritebackup
set noswapfile
" }}}
" Searching {{{
set ignorecase          " ignore case when searching
set incsearch           " Search as characters are entered
set hlsearch            " Highlight matches
nnoremap <leader><space> :nohlsearch<CR> " turn off search highlight
"
" }}}
" Folding {{{
set foldmethod=indent   " fold based on indent level
set foldnestmax=10      " max 10 depth
set foldenable
nnoremap <space> za
set foldlevelstart=10    " start with fold level of 1
" }}}
" Custom Functions {{{
" Word processor mode
func! WordProcessorMode() 
  setlocal formatoptions=1 " don't include linebreaks
  setlocal linebreak " break visually
  setlocal wrap
  setlocal nolist 
  "  setlocal breakat=\ |@-+;:,./?^I
  setlocal noexpandtab
  setlocal foldcolumn=3 
  setlocal nuw=5
  "setlocal columns=72

  nnoremap j gj
  nnoremap k gk
  vnoremap j gj
  vnoremap k gk

  setlocal spell spelllang=de 
  set complete+=s
  set formatprg=par
endfu 
com! WP call WordProcessorMode()

function! ToggleNumber()
    if(&relativenumber == 1)
        set norelativenumber
        set number
    else
        set relativenumber
    endif
endfunc

" }}}

" Movement
" =========
" bind Ctrl+<movement> keys to move around the windows, instead of using Ctrl+w + <movement>
" map <c-j> <c-w>j
" map <c-k> <c-w>k
" map <c-l> <c-w>l
" map <c-h> <c-w>h

" vim:foldmethod=marker:foldlevel=0
