#!/bin/sh

fullFileName=$1

suffix=${fullFileName#*.}

if [ "$suffix" != "zip" ];then
  echo "Must be a valid zip file"
else
  filename=${fullFileName%.*}
  echo "filename: $filename"
  echo "now unzip $1 and use idea $1"
  unzip $1 && idea $filename
fi
